version: "3"
networks:
  expense:
volumes:
  mysql:
services:
  mysql:
    image: mohansai7/mysql:v1
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  backend:
    image: mohansai7/backend:v1
    container_name: backend
    command: sh -c "sleep 10 && node /opt/server/index.js"
    depends_on:
    - mysql
  frontend:
    image: mohansai7/frontend:v1
    container_name: frontend
    ports:
    - 80:80
    depends_on:
    - backend